spring.application.name=gateway

# JWT Configuration
jwt.secret=5567586B58703273357638792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=3600000

# Disable Docker Compose support (since Docker is not installed)
spring.docker.compose.enabled=false

# Example Routes
# Pattern -> Target URL
gateway.routes./api/users/**=http://localhost:8081
gateway.routes./api/products/**=http://localhost:8082
